site_name: My GKMIT Team Experience Report
site_description: A report on my experience with different teams at GKMIT
site_author: Kamlesh Chandel

# Theme configuration with unique colors
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  
  icon:
    repo: fontawesome/brands/github

# Navigation structure
nav:
  - My Favorite Team: index.md
  - Favorite Project - KGeN: favorite_project.md
  - Favorite Project - FitBudd: fitbudd_project.md
  - 2 Weeks Internship Report: weekly_report.md

# Extensions for better formatting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

